ALTER TABLE `users`
    MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'FRONT_DESK', 'ACCOUNTANT', 'GUEST') NOT NULL DEFAULT 'GUEST';

ALTER TABLE `property_assignments`
    MODIFY `role` ENUM('ADMIN', 'MANAGER', 'FRONT_DESK', 'ACCOUNTANT') NOT NULL;
